---
- name: enable alerts
  k8s:
    api_key: "{{ api_key }}"
    name: alertmanager-main
    namespace: openshift-monitoring
    definition:
      kind: Secret
      data:
        alertmanager.yaml: "{{ alert_manager | string | b64encode }}"
  vars:
    alert_manager:
      global:
        resolve_timeout: 5m
        slack_api_url: "{{ ocp_alert_manager_slack_url }}"
      receivers:
        - name: Default
          slack_configs:
            - channel: "{{ ocp_alert_manager_slack_channel }}"
      route:
        group_by:
          - namespace
        group_interval: 5m
        group_wait: 30s
        receiver: Default
        repeat_interval: 12h
        routes:
          - receiver: Default
            match:
              alertname: Watchdog