- name: setup ocp console setting
  hosts: all
  gather_facts: false
  module_defaults:
    group/k8s:
      state: 'present'
      host: "{{ api_url }}"
      api_key: "{{ api_key }}"
      validate_certs: "{{ validate_certs | default('true') }}"
      ca_cert: "{{ ocp_api_root_cert_file | default('omit') }}"

  tasks:

    - include_role:
        name: ocp-console
