- name: setup fevermap
  hosts: all
  gather_facts: false
  module_defaults:
    group/k8s:
      state: 'present'
      host: "{{ api_url }}"
      api_key: "{{ api_key }}"
      namespace: "{{ project_name }}"
      validate_certs: "{{ validate_certs | default('true') }}"
      ca_cert: "{{ ocp_api_root_cert_file }}"

  tasks:

    - include_role:
        name: ocp-project
      tags: project
