- name: deploy the nfs provisioner
  hosts: all
  gather_facts: false
  module_defaults:
    group/k8s:
      state: 'present'
      host: "{{ api_url }}"
      api_key: "{{ api_key }}"
      validate_certs: false
      ca_cert: "{{ ocp_api_root_cert_file | default('omit') }}"

  tasks:

    - include_role:
        name: ocp-nfs-provisioner
