---
- name: create ldap bind secret
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      data:
        bindPassword: "{{ ocp_ldap_bind_password | b64encode }}"
      metadata:
        name: ldap-secret
        namespace: openshift-config
      type: Opaque
  tags:
    - ldap
    - ldap_auth

- name: set the user-ca-bundle for ldap to use
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ca-config-map
        namespace: openshift-config
      data:
        ca.crt: "{{ lookup('file', ocp_ldap_ca_cert, rstrip=False) }}"
  tags:
    - ldap
    - ldap_auth

- name: configure ldap autentication
  k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders:
        - name: ldap
          challenge: false
          login: true
          mappingMethod: claim
          type: LDAP
          ldap:
            attributes:
              id:
              - dn
              email:
              - mail
              name:
              - cn
              preferredUsername:
              - uid
            bindDN: "{{ ocp_ldap_bind_dn }}"
            bindPassword:
              name: ldap-secret
            ca:
              name: ca-config-map
            insecure: false
            url: "{{ ocp_ldap_url }}"
        tokenConfig:
          accessTokenMaxAgeSeconds: 86400
  tags:
    - ldap
    - ldap_auth

- name: enable ldap group sync cronjob
  k8s:
    definition:
      "{{ item }}"
  loop: "{{ ldap_group_sync_cron_job }}"
  tags:
    - ldap
    - ldap_group_sync
